apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: xig49y4xw-go 
  janus-idp.io/tekton: xig49y4xw-go
  backstage.io/kubernetes-id: xig49y4xw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xig49y4xw-go
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml