apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: xig49y4xw-go
  janus-idp.io/tekton: xig49y4xw-go
  backstage.io/kubernetes-id: xig49y4xw-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: xig49y4xw-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
